name = "home"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[assets]
directory = ".svelte-kit/cloudflare"

[[routes]]
pattern = "about.reesuke.com/*"
zone_name = "reesuke.com"
